###########
# site.title
# host: 0.0.0.0
theme: minima
title: Jario 
name: Jario 
description: > # this means to ignore newlines until "baseurl:"
 .
permalink: ':title/'
#baseurl: "/linux.gitub.io" # the subpath of your site, e.g. /blog
#url: "https://logs.jar.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: jarioswami #if your site has a twitter account, enter it here

# Author Settings
author: Jario Swami # add your name
#author-img: avatar.png # add your photo
#about-author:  Jario estudo física, gestão ambiental e pedagogia na universidade. É mestre de yoga e defensor de um estilo de vida minimalista.
#google_analytics: G-0PV74153TH 

#########################
# more settings

plugins:
  - jekyll-paginate
  - jekyll-sitemap  
  - jekyll-feed
  - jekyll-redirect-from
    
whitelist:
  - jekyll-redirect-from

markdown: kramdown

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
    social_links:
       - { platform: devto,          user_url: "https://dev.to/jario" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
      - { platform: github,         user_url: "https://github.com/jario" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
      - { platform: instagram,      user_url: "https://www.instagram.com/1.jario" }
      - { platform: keybase,        user_url: "https://keybase.io/jario" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jario" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
      - { platform: telegram,       user_url: "https://t.me/jarioswami" }
      - { platform: twitter,        user_url: "https://twitter.com/_jario" }
      - { platform: youtube,        user_url: "https://www.youtube.com/@jarioswami" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false


permalink: /:slug
timezone: America/Sao_Paulo
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

